<a href="https://colab.research.google.com/github/Satya-slav/ML_zoomcamp-2026/blob/main/homework1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Satya

for data loading...

In [2]:
import pandas as pd
import numpy as np
df=pd.read_csv('car_fuel_efficiency_2026.csv')
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

q1- pandas version

In [3]:
pd.__version__

'2.2.3'

q2- Records count

In [4]:
len(df)

10000

q3-Fuel type

In [7]:
df['fuel_type'].nunique()

3

q4-missing values

In [9]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

q5-max fuel efficiency

In [10]:
df['fuel_efficiency_mpg'].max()

41.2

q6 median value of horsepower

In [28]:
median_before = df['horsepower'].median()
mean_hp = df['horsepower'].mean()
df_filled = df['horsepower'].fillna(mean_hp)
median_after = df_filled.median()
print("Median before:", median_before)
print("Median after:", median_after)

Median before: 254.0
Median after: 254.44601556505535

q7 sum of weights

In [31]:
import numpy as np
asia_df = df[df['origin'] == 'Asia'][['engine_displacement', 'horsepower', 'vehicle_weight']].dropna()
X = asia_df.iloc[:9].values
XTX = X.T @ X
XTX_inv = np.linalg.inv(XTX)
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
w = XTX_inv @ X.T @ y
print("Sum of weights:", w.sum())

Sum of weights: 9.697343961017856